# Generated by Django 4.2.1 on 2023-05-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='member',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='seat_position',
        ),
    ]
